name: permission_handler_html_example
description: Demonstrates how to use the permission_handler_html plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  baseflow_plugin_template:
    git:
      url: https://github.com/hugochou/baseflow_plugin_template.git
      ref: flutter_1.22.6
  flutter:
    sdk: flutter

dev_dependencies:
#  integration_test:
#    sdk: flutter
  flutter_test:
    sdk: flutter

  permission_handler_html:
    # When depending on this package from a real application you should use:
    #   permission_handler_web: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  url_launcher: ^5.7.10

flutter:
  uses-material-design: true
