name: permission_handler_windows
description: Permission plugin for Flutter. This plugin provides the Windows API to request and check permissions.
version: 0.2.0
homepage: https://github.com/baseflow/flutter-permission-handler

flutter:
  plugin:
    implements: permission_handler
    platforms:
      windows:
        pluginClass: PermissionHandlerWindowsPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface:
    git:
      url: https://github.com/hugochou/flutter-permission-handler.git
      path: permission_handler_platform_interface
      ref: flutter_1.22.6

dependency_overrides:
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^1.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.2"
