name: permission_handler_android
description: Permission plugin for Flutter. This plugin provides the Android API to request and check permissions.
homepage: https://github.com/baseflow/flutter-permission-handler
version: 12.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.2"

flutter:
  plugin:
    implements: permission_handler
    platforms:
      android:
        package: com.baseflow.permissionhandler
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface:
    git:
      url: https://github.com/hugochou/flutter-permission-handler.git
      path: permission_handler_platform_interface
      ref: flutter_1.22.6

dependency_overrides:
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface

dev_dependencies:
#  flutter_lints:
  plugin_platform_interface: ^1.0.3
