name: permission_handler_apple
description: Permission plugin for Flutter. This plugin provides the iOS API to request and check permissions.
repository: https://github.com/baseflow/flutter-permission-handler
issue_tracker: https://github.com/Baseflow/flutter-permission-handler/issues
version: 9.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.2"

flutter:
  plugin:
    implements: permission_handler
    platforms:
      ios:
        pluginClass: PermissionHandlerPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface:
    git:
      url: https://github.com/hugochou/flutter-permission-handler.git
      path: permission_handler_platform_interface
      ref: flutter_1.22.6

dependency_overrides:
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface


dev_dependencies:
#  flutter_lints:
  plugin_platform_interface: ^1.0.3
