name: permission_handler_html
description: Permission plugin for Flutter. This plugin provides the web API to request and check permissions.
version: 0.1.0+2
homepage: https://github.com/baseflow/flutter-permission-handler

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  permission_handler_platform_interface:
    git:
      url: https://github.com/hugochou/flutter-permission-handler.git
      path: permission_handler_platform_interface
      ref: flutter_1.22.6

dependency_overrides:
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints:
  mockito: ^4.1.4
  build_runner: ^1.11.1+1
  test: ^1.15.7

flutter:
  plugin:
    implements: permission_handler
    platforms:
      web:
        pluginClass: WebPermissionHandler
        fileName: permission_handler_html.dart
