name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
repository: https://github.com/baseflow/flutter-permission-handler
issue_tracker: https://github.com/Baseflow/flutter-permission-handler/issues
version: 11.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.2"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android
      ios:
        default_package: permission_handler_apple
#      web:
#        default_package: permission_handler_html
#      windows:
#        default_package: permission_handler_windows

dependencies:
  flutter:
    sdk: flutter
  meta:
  permission_handler_android:
    path: ../permission_handler_android
#    git:
#      url: https://github.com/hugochou/flutter-permission-handler.git
#      ref: flutter_1.22.6
  permission_handler_apple:
    path: ../permission_handler_apple
#    git:
#      url: https://github.com/hugochou/flutter-permission-handler.git
#      ref: flutter_1.22.6
#  permission_handler_html:
#    path: ../permission_handler_html
#  permission_handler_windows:
#    path: ../permission_handler_windows
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface
#    git:
#      url: https://github.com/hugochou/flutter-permission-handler.git
#      ref: flutter_1.22.6

dependency_overrides:
  permission_handler_android:
    path: ../permission_handler_android
  permission_handler_apple:
    path: ../permission_handler_apple
  permission_handler_platform_interface:
    path: ../permission_handler_platform_interface

dev_dependencies:
#  flutter_lints:
#  flutter_test:
#    sdk: flutter
  mockito: ^4.1.4
  plugin_platform_interface: ^1.0.3
